name: Update zig-dev

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */8 * * *

jobs:
  update-zig-dev:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          scripts/zig-dev.sh
