name: Update zig-dev & zls-dev

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */8 * * *

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Configure Git user
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Update
        run: |
          scripts/update.sh zig-dev zls-dev
